// Package ec2instance provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.12.2 DO NOT EDIT.
package ec2instance

import (
	"time"
)

// AWSEvent defines model for AWSEvent.
type AWSEvent struct {
	Account    string                           `json:"account"`
	Detail     EC2InstanceLaunchLifecycleAction `json:"detail"`
	DetailType string                           `json:"detail-type"`
	Id         string                           `json:"id"`
	Region     string                           `json:"region"`
	Resources  []string                         `json:"resources"`
	Source     string                           `json:"source"`
	Time       time.Time                        `json:"time"`
	Version    string                           `json:"version"`
}

// EC2InstanceLaunchLifecycleAction defines model for EC2InstanceLaunchLifecycleAction.
type EC2InstanceLaunchLifecycleAction struct {
	AutoScalingGroupName string `json:"AutoScalingGroupName"`
	Destination          string `json:"Destination"`
	EC2InstanceId        string `json:"EC2InstanceId"`
	LifecycleActionToken string `json:"LifecycleActionToken"`
	LifecycleHookName    string `json:"LifecycleHookName"`
	LifecycleTransition  string `json:"LifecycleTransition"`
	NotificationMetadata string `json:"NotificationMetadata"`
	Origin               string `json:"Origin"`
}
